name: Check Requirements are up to date

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true

env:
  NAMESPACE: paloaltonetworks
  COLLECTION_NAME: panos

jobs:
  needs-update:
    name: Need Requirements Update
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.8.5"

      - name: Install dependencies
        run: poetry install

      - name: Install temp dependencies
        run: poetry run pip install toml

      - name: Make requirements.txt
        run: poetry run make reqs

      - name: Check for changes in requirements.txt
        run: |
          if git diff --exit-code requirements.txt; then
            echo "✅ No changes in requirements.txt"
          else
            echo "❌ requirements.txt is outdated. Please update it with "make reqs" and commit the changes."
            exit 1
          fi
