---
on: [push, pull_request]
name: Tox
jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: python -m pip install tox
      - name: Move to tox conf file and run tox
        run: | 
          cd .github/workflows
          python -m tox -- ../..